### ISSUE TITLE
[Dev/Scrum]Design Interface

### ISSUE THREAD

**Issue by tienkim9920** [tienkim9920/cnpm_shopping#6]
- [ ] Sign In Page
- [ ] Sign Up Page
- [ ] Home Page
- [ ] Product Page
- [ ] Detail Product Page
- [ ] Cart Page
- [ ] Checkout Page
- [ ] Order Page
- [ ] Forget Password Page
- [ ] Profile Page
- [ ] Payment Page
- [ ] History Page
- [ ] Detail Order Page
- [ ] Delivery Page

**Comment by ToanNguyen197** [comment]
Im done
